const CATEGORY_LABELS={basic:'基本',tile:'牌',table:'卓・進行',action:'操作',state:'状態',rule:'ルール',score:'点数','hand-shape':'手牌の形',strategy:'考え方',defense:'守備',yaku:'役'};
const KANA_GROUPS=[['あ','あいうえお'],['か','かきくけこがぎぐげご'],['さ','さしすせそざじずぜぞ'],['た','たちつてとだぢづでど'],['な','なにぬねの'],['は','はひふへほばびぶべぼぱぴぷぺぽ'],['ま','まみむめも'],['や','やゆよ'],['ら','らりるれろ'],['わ','わをん']];
const norm=s=>(s||'').toString().normalize('NFKC').toLowerCase().replace(/\s+/g,'');
const kataToHira=s=>(s||'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
function kanaGroup(reading){const c=kataToHira(reading)[0]||'';return KANA_GROUPS.find(([,chars])=>chars.includes(c))?.[0]||'他'}
function relatedLinks(term,ctx){return (term.relatedTerms||[]).map(id=>ctx.termById.get(id)).filter(Boolean).map(t=>`<a href="#dictionary?term=${encodeURIComponent(t.id)}">${t.nameJa}</a>`).join('、')||'なし'}
function lessonLinks(term,ctx){return (term.lessonRefs||[]).map(id=>ctx.lessonById.get(id)).filter(Boolean).map(l=>`<a href="#${l.id}">${l.title}</a>`).join('、')||'なし'}
function yakuAsSearchEntry(y){return {id:y.id,nameJa:y.displayNameJa||y.nameJa,readingJa:y.readingJa,readingKana:y.readingJa,aliases:[y.nameJa,...(y.aliases||[])].filter(Boolean),category:'yaku',shortDescription:y.summary,isYaku:true,yakuId:y.id}}

export function renderDictionary(app,ctx){
  const params=new URLSearchParams((location.hash.split('?')[1]||''));const selectedId=params.get('term');const selected=ctx.termById.get(selectedId);
  if(selected){app.innerHTML=`<section class="lesson-head"><div class="eyebrow">用語集</div><h1>${selected.nameJa}</h1><p class="lead">${selected.readingJa}（${selected.readingKana}）</p></section><section class="panel"><h2>意味</h2><p>${selected.shortDescription}</p>${selected.aliases?.length?`<p><strong>別の呼び方：</strong>${selected.aliases.join('、')}</p>`:''}<p><strong>分類：</strong>${CATEGORY_LABELS[selected.category]||selected.category}</p><p><strong>関連用語：</strong>${relatedLinks(selected,ctx)}</p><p><strong>関連する解説：</strong>${lessonLinks(selected,ctx)}</p></section><div class="lesson-nav"><a class="secondary" href="#dictionary">用語集へ戻る</a><a class="primary" href="#home">ホームへ</a></div>`;return}
  const entries=[...ctx.terms,...ctx.yaku.filter(y=>y.standard).map(yakuAsSearchEntry)].sort((a,b)=>a.readingKana.localeCompare(b.readingKana,'ja'));
  app.innerHTML=`<section class="lesson-head"><div class="eyebrow">調べる</div><h1>麻雀用語集</h1><p class="lead">用語と標準役を、漢字・ひらがな・カタカナ・別名からまとめて検索できます。読み方がわからなくても、分類や五十音から探せます。</p></section><section class="panel"><div class="search-row"><label class="search-label">用語・役を検索<input id="term-search" type="search" inputmode="search" placeholder="例：フリテン、振聴、りーち、ピンフ"></label><label>分類<select id="term-category"><option value="">すべて</option>${[...new Set(entries.map(t=>t.category))].map(c=>`<option value="${c}">${CATEGORY_LABELS[c]||c}</option>`).join('')}</select></label></div><div class="kana-nav"><button type="button" data-kana="">すべて</button>${KANA_GROUPS.map(([k])=>`<button type="button" data-kana="${k}">${k}行</button>`).join('')}</div><p id="term-count" class="muted"></p><div id="term-results" class="glossary-grid"></div></section><div class="lesson-nav"><a class="secondary" href="#home">ホームへ戻る</a><a class="primary" href="#yaku-guide">役図鑑を見る</a></div>`;
  let kana='';const input=app.querySelector('#term-search'),cat=app.querySelector('#term-category'),out=app.querySelector('#term-results'),count=app.querySelector('#term-count');
  const draw=()=>{const q=norm(kataToHira(input.value));const rows=entries.filter(t=>{const hay=norm(kataToHira([t.nameJa,t.readingJa,t.readingKana,...(t.aliases||[])].join('')));return (!q||hay.includes(q))&&(!cat.value||t.category===cat.value)&&(!kana||kanaGroup(t.readingKana)===kana)});count.textContent=`${rows.length}件表示（用語＋標準役）`;out.innerHTML=rows.map(t=>`<a class="glossary-card" href="${t.isYaku?`#yaku-guide?yaku=${encodeURIComponent(t.yakuId)}`:`#dictionary?term=${encodeURIComponent(t.id)}`}"><span class="glossary-reading">${t.readingJa}</span><strong>${t.nameJa}</strong><small>${t.shortDescription}</small>${t.isYaku?'<span class="glossary-kind">役図鑑へ</span>':''}</a>`).join('')||'<p>該当する用語・役がありません。</p>'};
  input.oninput=draw;cat.onchange=draw;app.querySelectorAll('[data-kana]').forEach(b=>b.onclick=()=>{kana=b.dataset.kana;app.querySelectorAll('[data-kana]').forEach(x=>x.classList.toggle('active',x===b));draw()});draw();
}
